CREATE TABLE tblSuff(				
	attrbSuff_ID 			VARCHAR2(7),
	attrbSuff_EnterDate		DATE			NOT NULL,
	attrbSuff_EnterMentor	VARCHAR2(20)	NOT NULL,
	attrbSuff_EnterDomain1	NUMBER	(1,0)	NOT NULL,
	attrbSuff_EnterDomain2	NUMBER	(1,0)	NOT NULL,
	attrbSuff_EnterDomain3	NUMBER	(1,0)	NOT NULL,
	attrbSuff_EnterDomain4	NUMBER	(1,0)	NOT NULL,
	attrbSuff_EnterDomain5	NUMBER	(1,0)	NOT NULL,
	attrbSuff_EnterDomain6	NUMBER	(1,0)	NOT NULL,
	attrbSuff_EnterDomain7	NUMBER	(1,0)	NOT NULL,
	attrbSuff_EnterDomain8	NUMBER	(1,0)	NOT NULL,
	attrbSuff_EnterDomain9	NUMBER	(1,0)	NOT NULL,
	attrbSuff_ExitDate		DATE			NOT NULL,
	attrbSuff_ExitMentor	NUMBER	(1,0)	NOT NULL,
	attrbSuff_ExitDomain1	NUMBER	(1,0)	NOT NULL,
	attrbSuff_ExitDomain2	NUMBER	(1,0)	NOT NULL,
	attrbSuff_ExitDomain3	NUMBER	(1,0)	NOT NULL,
	attrbSuff_ExitDomain4	NUMBER	(1,0)	NOT NULL,
	attrbSuff_ExitDomain5	NUMBER	(1,0)	NOT NULL,
	attrbSuff_ExitDomain6	NUMBER	(1,0)	NOT NULL,
	attrbSuff_ExitDomain7	NUMBER	(1,0)	NOT NULL,
	attrbSuff_ExitDomain8	NUMBER	(1,0)	NOT NULL,
	attrbSuff_ExitDomain9	NUMBER	(1,0)	NOT NULL,
	attrbSuff_Exit12Mo		VARCHAR2(1)		NOT NULL,
	attrbSuff_ExitAlt		VARCHAR2(10)	NOT NULL,
	CONSTRAINT PK_attrbSuff_ID
	PRIMARY KEY(attrbSuff_ID)
	);