CREATE TABLE tblExit(				
	attrbExit_ID			VARCHAR2(7),
	attrbExit_Date			DATE			NOT NULL,
	attrbExit_DWCDate		DATE			NOT NULL,
	attrbExit_HomePh		VARCHAR2(13)	NOT NULL,
	attrbExit_CellPh		VARCHAR2(13)	NOT NULL,
	attrbExit_AddrStreet	VARCHAR2(50)	NOT NULL,
	attrbExit_AddrCity		VARCHAR2(25)	NOT NULL,
	attrbExit_AddrState		VARCHAR2(2)		NOT NULL,
	attrbExit_AddrZip		NUMBER	(5,0)	NOT NULL,
	attrbExit_TotalContacts	NUMBER	(4,0)	NOT NULL,
	attrbExit_DWCOutcome	VARCHAR2(10)	NOT NULL,
	attrbExit_RecoveryYrs	NUMBER	(2,0)	NOT NULL,
	attrbExit_RecoveryMos	NUMBER	(2,0)	NOT NULL,
	attrbExit_RecoveryDays	NUMBER	(3,0)	NOT NULL,
	attrbExit_IncarcPostDWC	VARCHAR2(6)			NOT NULL,
	attrbExit_GiveBirth		VARCHAR2(1)			NOT NULL,
	attrbExit_ExitPosToxBaby	VARCHAR2(2)		NOT NULL,
	attrbExit_ExitTotNumChild	VARCHAR2(2)		NOT NULL,
	attrbExit_AgeOldest			NUMBER	(2,0)	NOT NULL,
	attrbExit_AgeYoungest		NUMBER	(2,0)	NOT NULL,
	attrbExit_EduStatus			VARCHAR2(35)	NOT NULL,
	attrbExit_ReltnStatus		VARCHAR2(35)	NOT NULL,
	attrbExit_EmplyStatus		VARCHAR2(35)	NOT NULL,
	attrbExit_CompletePhases	VARCHAR2(5)		NOT NULL,
	attrbExit_DrugTxComplete	VARCHAR2(1)		NOT NULL,
	attrbExit_TxName			VARCHAR2(35)	NOT NULL,
	attrbExit_TxCompMoYr		DATE			NOT NULL,
	attrbExit_LevelEngage		NUMBER	(1,0)	NOT NULL,
	attrbExit_RecovEngage		NUMBER	(1,0)	NOT NULL,
	attrbExit_Notes				VARCHAR2(500)	NOT NULL,
	attrbExit_LegalClosure		DATE			NOT NULL,
	attrbExit_LegalOutcome		VARCHAR2(25)	NOT NULL,
	attrbExit_LegalNote			VARCHAR2(500)	NOT NULL,
	CONSTRAINT PK_attrbExit_ID
	PRIMARY KEY (attrbExit_ID)
	);