CREATE TABLE tblRegistration(
	attrbReg_ID					VARCHAR2(7),
	attrbChild_ID				VARCHAR2(7),
	attrbReg_DatefirstContact	DATE				NOT NULL,
	attrbReg_DateDWCEnter		DATE				NOT NULL,
	attrbReg_MPrecruit			CHAR(1)				NOT NULL,
	attrbReg_Attyrecruit		CHAR(1)				NOT NULL,
	attrbReg_FnameParent		VARCHAR2(15)		NOT NULL,
	attrbReg_LnameParent		VARCHAR2(15)		NOT NULL,
	attrbReg_EnterHomePh		VARCHAR2(13)		NOT NULL,
	attrbReg_EnterCellPh		VARCHAR2(13)		NOT NULL,
	attrbReg_AddrStreet			VARCHAR2(30)		NOT NULL,
	attrbReg_AddrCity			VARCHAR2(25)		NOT NULL,
	attrbReg_AddrState			VARCHAR2(2)			NOT NULL,
	attrbReg_AddrZip			VARCHAR2(5)			NOT NULL,
	attrbReg_DOB				DATE				NOT NULL,
	attrbReg_Age				NUMBER	(2,0)		NOT NULL,
	attrbReg_Gender				VARCHAR2(1)			NOT NULL,
	attrbReg_EnterPreg			VARCHAR2(2)			NOT NULL,
	attrbReg_IncarcB4DWC		VARCHAR2(1)			NOT NULL,
	attrbReg_IncarcCurrent		VARCHAR2(1)			NOT NULL,
	attrbReg_EnterPosToxBaby	VARCHAR2(2)			NOT NULL,
	attrbReg_EnterEduStatus		VARCHAR2(35)		NOT NULL,
	attrbReg_EnterReltnStatus	VARCHAR2(35)		NOT NULL,
	attrbReg_EnterEmplyStatus	VARCHAR2(20)		NOT NULL,
	attrbReg_Ethnicity			VARCHAR2(25)		NOT NULL,
	attrbReg_Language			VARCHAR2(15)		NOT NULL,
	attrbReg_CurrTx				VARCHAR2(1)			NOT NULL,
	attrbReg_CurrTxName			VARCHAR2(35)		NOT NULL,
	attrbReg_TotNumChild		VARCHAR2(2)			NOT NULL,
	attrbReg_EnterAgeOldest		VARCHAR2(2)			NOT NULL,
	attrbReg_EnterAgeYoungest	VARCHAR2(2)			NOT NULL,
	attrbReg_AttyName			VARCHAR2(25)		NOT NULL,
	attrbReg_AttyPhone			VARCHAR2(13)		NOT NULL,
	attrbReg_SWname				VARCHAR2(25)		NOT NULL,
	attrbReg_SWPhone			VARCHAR2(13)		NOT NULL,
	attrbReg_Notes				VARCHAR2(255)		NOT NULL,
	CONSTRAINT PK_attrbReg_ID
	PRIMARY KEY (attrbReg_ID),
	CONSTRAINT FK_attrbChild_ID
	FOREIGN KEY (attrbChild_ID) REFERENCES tblChild
	);