CREATE TABLE tblSatisf (				
	attrbSatisf_ID 			VARCHAR2(7),
	attrbSatisf_Date		DATE			NOT NULL,
	attrbSatisf_MP			VARCHAR2(15)	NOT NULL,
	attrbSatisf_3help		VARCHAR2(50)	NOT NULL,
	attrbSatisf_3improve	VARCHAR2(50)	NOT NULL,
	attrbSatisf_St1		NUMBER	(1,0)	NOT NULL,
	attrbSatisf_St2		NUMBER	(1,0)	NOT NULL,
	attrbSatisf_St3		NUMBER	(1,0)	NOT NULL,
	attrbSatisf_St4		NUMBER	(1,0)	NOT NULL,
	attrbSatisf_St5		NUMBER	(1,0)	NOT NULL,
	attrbSatisf_St6		NUMBER	(1,0)	NOT NULL,
	attrbSatisf_St7		NUMBER	(1,0)	NOT NULL,
	attrbSatisf_St8		NUMBER	(1,0)	NOT NULL,
	attrbSatisf_St9		NUMBER	(1,0)	NOT NULL,
	attrbSatisf_St10	NUMBER	(1,0)	NOT NULL,
	attrbSatisf_St11	NUMBER	(1,0)	NOT NULL,
	attrbSatisf_St12	NUMBER	(1,0)	NOT NULL,
	attrbSatisf_St13	NUMBER	(1,0)	NOT NULL,
	attrbSatisf_St14	NUMBER	(1,0)	NOT NULL,
	attrbSatisf_St15	NUMBER	(1,0)	NOT NULL,
	attrbSatisf_St16	NUMBER	(1,0)	NOT NULL,
	attrbSatisf_St17	NUMBER	(1,0)	NOT NULL,
	attrbSatisf_St18	NUMBER	(1,0)	NOT NULL,
	attrbSatisf_St19	NUMBER	(1,0)	NOT NULL,
	attrbSatisf_St20	NUMBER	(1,0)	NOT NULL,
	attrbSatisf_St21	NUMBER	(1,0)	NOT NULL,
	attrbSatisf_St22	NUMBER	(1,0)	NOT NULL,
	attrbSatisf_St23	NUMBER	(1,0)	NOT NULL,
	attrbSatisf_St24	NUMBER	(1,0)	NOT NULL,
	attrbSatisf_St25	NUMBER	(1,0)	NOT NULL,
	attrbSatisf_St26	NUMBER	(1,0)	NOT NULL,
	attrbSatisf_St27	NUMBER	(1,0)	NOT NULL,
	attrbSatisf_St28	NUMBER	(1,0)	NOT NULL,
	attrbSatisf_St29	NUMBER	(1,0)	NOT NULL,
	attrbSatisf_St30	NUMBER	(1,0)	NOT NULL,
	CONSTRAINT PK_attrbSatisf_ID
	PRIMARY KEY (attrbSatisf_ID)
	);